version: '3'
services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      - onlyoffice

  app:
    container_name: app-server
    image: nextcloud:fpm-alpine
    stdin_open: true
    tty: true
    restart: always
    environment:
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
    env_file:
      - db.env
    expose:
      - '80'
      - '9000'
    networks:
      - onlyoffice
    volumes:
      - app_data:/var/www/html

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice

  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 8080:80
      - 443:443
    networks:
      - onlyoffice
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=961101
    env_file:
      - db.env
    networks:
      - onlyoffice

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - app_data:/var/www/html
    entrypoint: /cron.sh
    networks:
      - onlyoffice

networks:
  onlyoffice:
    driver: 'bridge'

volumes:
  document_data:
  document_log:
  app_data:
  mysql_data: